### PR TITLE
Sensu Bonsai Updates

### PR DESCRIPTION
**Pull request by asachs01**
Greetings @m17ch & team!

Here's the PR to enable the Goalert handler to be used with Bonsai. I've done a pre-release and confirmed that it's been uploaded to Bonsai successfully: 

https://bonsai.sensu.io/assets/asachs01/sensu-go-goalert

I'll be happy to delete/deprecate that once the official Target version is on Bonsai. 

There are a couple of notes here:

* Since `etcd` is "stable" on Linux/amd64 && ppc64le, I've only added Linux/amd64 as the only released asset. This is due to the fact that handlers are executed on the backend, not the agents. Any additional OS's can be added fairly easily
* We have some badges available, and I've already set them to point to the `target` namespace in anticipation of this being uploaded to bonsai
* There is a change that will need to be made in the README (ln #12) to point to the version that you choose to use when releasing the asset under Target's namespace
* Using Travis will require a GITHUB_TOKEN to be set (the token will just need the `repo` scope

Let me know if there are any questions I can answer, about this, or anything that I might have done that wasn't up to scratch.

### CODE REVIEW

**Comment by asachs01** [comment]
Howdy @m17ch ! 👋 Not sure if you've had a chance to take a gander at this yet. Let me know if there's anything I need to change here.

**Comment by m17ch** [comment]
Hi @asachs01 -- very sorry for the delay on this.  The team will be trying to get this reviewed/merged as soon as possible (hopefully early next week).  We'll holler at you if we run into any questions/concerns -- thanks a ton for helping with this!

**Comment by asachs01** [comment]
No sweat! Glad to help :)

**Review by m17ch — APPROVED** [review]
LGTM 👍 

I believe I've taken care of all requirements -- thank you very much for helping with this, @asachs01 !

**Pull request merged**
